### ISSUE TITLE
How about add CODE_OF_CONDUCT.md to LaunchPAD_JS?

### ISSUE THREAD

**Issue by bbvch13531** [rouismia/LaunchPAD_JS#6]
Type of issue
 - Doc

Description
- I think opensource project should have code of conduct. 😄
How about add CODE_OF_CONDUCT.md to LaunchPAD_JS?
If this looks good on you, could I send PR that add CODE_OF_CONDUCT.md?

**Comment by rouismia** [comment]
I really appreciate of your advice.
It has added little moment ago.

**Comment by bbvch13531** [comment]
Thank you for your kindness @rouismia 👍
